### ISSUE TITLE
Populating found maps fails when a single texture in folder does not match substance format

### ISSUE THREAD

**Issue by BigRoy** [Strangenoise/SubstancePainterToMaya#1]
### Issue

When you have other images in the textures folder that do not match the naming structure (e.g. doesn't have the `_` delimiters) the script fails with an error.

It fails on [this line](https://github.com/Strangenoise/SubstancePainterToMaya/blob/1fcb6445a2b4335b8d503c5f5c308a2395f478e7/SubstancePainterToMaya/main.py#L475)

Here's a traceback:

```python
# Traceback (most recent call last):
#   File "P:\pipeline\2.1_dev\git\SubstancePainterToMaya\SubstancePainterToMaya\main.py", line 192, in <lambda>
#     self.launchButton.clicked.connect(lambda: self.launch())
#   File "P:\pipeline\2.1_dev\git\SubstancePainterToMaya\SubstancePainterToMaya\main.py", line 390, in launch
#     self.populateFoundMaps()
#   File "P:\pipeline\2.1_dev\git\SubstancePainterToMaya\SubstancePainterToMaya\main.py", line 476, in populateFoundMaps
#     mapName = item.split(mapPosSeparator)[mapPos].split('.')[0]
# IndexError: list index out of range
```
_Note: Line number traceback might differ since I started playing a bit with the code_

### Solution

Ignore any files that do not match the requested filename structure.

**Comment by Strangenoise** [comment]
Done :)
