### ISSUE TITLE
Default image path goes to "sourceimages" and ignores workspace file rules

### ISSUE THREAD

**Issue by BigRoy** [Strangenoise/SubstancePainterToMaya#2]
### Issue

Maya allows to customize the filerule for sourceimages, it is where Maya guesses the source images should be. A studio can customize this to set a different default behavior. It would be a good start for this tool too look too.

### Solution

Implement the default search path using the `sourceImages` file rule. Here's the code:

```python
import maya.cmds as mc

root_directory = mc.workspace(query=True, rootDirectory=True)
source_images_rule = mc.workspace(fileRuleEntry="sourceImages")
path = os.path.join(root_director, source_images_rule)
if os.path.exists(path):
    default = path
else:
    # Set default path only if the folder exists otherwise
    # leave it empty so it's easier to the user to set it manually?
    default = ""
```

**Comment by Strangenoise** [comment]
Done :)
