### ISSUE TITLE
Cancelling browsing Texture Folder raises NoneType error

### ISSUE THREAD

**Issue by BigRoy** [Strangenoise/SubstancePainterToMaya#3]
### Issue

When browsing by clicking the *Get* button for the Texture Folder and then cancelling by clicking "Cancel" or Escape an error is reported.

```python
# Traceback (most recent call last):
#   File "P:\pipeline\2.1_dev\git\SubstancePainterToMaya\SubstancePainterToMaya\main.py", line 101, in <lambda>
#     self.getButton.clicked.connect(lambda: self.getTextureFolder())
#   File "P:\pipeline\2.1_dev\git\SubstancePainterToMaya\SubstancePainterToMaya\main.py", line 576, in getTextureFolder
#     workDirectory = mc.fileDialog2(startingDirectory=sourceImages, fileMode=2, okCaption='Select')[0]
# TypeError: 'NoneType' object has no attribute '__getitem__'
```

### Solution

Capture the cancellation elegantly. When [the `mc.fileDialog2` returns a None value](https://github.com/Strangenoise/SubstancePainterToMaya/blob/1fcb6445a2b4335b8d503c5f5c308a2395f478e7/SubstancePainterToMaya/main.py#L571) then it should just return and do nothing.

**Comment by Strangenoise** [comment]
Thanks, it as been corrected :)
